### ISSUE TITLE
Integrate with InfoAid

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/refugees-welcome-croatia-web#17]
Check options to integrate with data source for this app:

InfoAid mobile app (http://bit.ly/infoaid), which is dedicated to providing information to and feedback from the refugee community in their native languages.

Speak with Hans

**Comment by synesenom** [comment]
Hi,

What kind of integration do you mean?

**Comment by schlos** [comment]
We're waiting for InfoAid developer here :)

I meant, feed our information to them, and use their information on our services.

**Comment by synesenom** [comment]
I am one of the developers behind InfoAid :)

**Comment by schlos** [comment]
can we get more detailed information about structure of information you need for publishing? Do you have any guidelines what is format or content of news you share?

format of message (or examples) would help us to know what information you need, what lenght, what categories/topics

details like text message max lenght (number of chars), location? (in which format?),, title? (needed, not needed), category (what are fixed categories), picture (if possible?? dimensions), information like that (edited)

also can you fetch those information from RSS feed?
we can plan seperate category in welcome.cms.hr for this needs with short information that you can plublish on InfoAid.

**Comment by synesenom** [comment]
Hi there,

So,
1) Length should be kept short (basically because Parse seems to have a limit on data size and with arabic font this can be a problem). Our rule of thumb is keeping it below 1000 characters, but not that sure about it.
2) Format is raw text, no pictures (yet) and a title.
3) At the moment we have no categories, but we have 'channels' that are cities in Hungary. The plan is to extend and replace cities by countries, Croatia will be the first of the external countries.
4) We don't fetch data from RSS feed, because we are pretty cautious about the messages we send out and also because the translation is not automatized yet (we are working on that).

The way we plan to do it is the following:
1) We provide you a web UI where you can send a message in English
2) We provide the translators who then translate the message to the supported languages (Arabic, Farsi, Pashto, Urdu, and we will add further ones later).
3) Once the translations are done, you get them and either you send them from the UI or we do it. IMHO, letting you send it would lift some weights from our shoulders.
4) We provide the app and all infrastructure.

For this to work, we need from Croatia:
1) 1-2 admins who manage the message sending interface
2) Some people responsible for gathering the news. We prefer keeping the admins and news collectors separate for various reasons (our experience is that this way is more robust and more trustworthy).

As we have a limited number of translators yet, we prefer keeping the number of messages low, only very important ones. However, as our translator team increases and once we launch our system that manages translations automatically, it won't become a problem. Just for now, because many things are done by hand.

**Comment by schlos** [comment]
1) We provide you a web UI where you can send a message in English

--> OK, can you support POST requests for News from Croatia in English language? We'd like to generate as less workload on our volunteers as possible. Since they will be working with several tools, one more is really additional unnecessary workload for them.

2) We provide the translators who then translate the message to the supported languages (Arabic, Farsi, Pashto, Urdu, and we will add further ones later).

--> OK

3) Once the translations are done, you get them and either you send them from the UI or we do it. IMHO, letting you send it would lift some weights from our shoulders.

--> as said above, we'd like to help our volunteers. can you automate it, or you'd like to approve our submissions before posting for public?

4) We provide the app and all infrastructure.

--> OK

Let me know possibilities for (1).

**Comment by schlos** [comment]
As agreed via email between CMS and InfoAid (Hans), InfoAid will use News Feed on English language from welcome.cms.hr at their own discretion:
- web http://welcome.cms.hr/index.php/en/category/news/
- rss feed http://welcome.cms.hr/index.php/en/category/news/feed/
